# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'reactNativeDemo' do
  pod 'React', path: '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]
  pod 'react-native-camera', path: '../node_modules/react-native-camera'
end
